'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _a_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_a_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _a_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_a_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _a_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_a_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _a_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_a_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _ah13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_ah13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _ah3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_ah3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _b_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_b_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _b_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_b_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _b_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_b_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _b_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_b_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _bh13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_bh13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _bh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_bh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _c_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_c_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _c_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_c_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _c_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_c_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _c_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_c_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _ch13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_ch13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _ch3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_ch3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _e_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_e_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _e_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_e_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _e_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_e_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _e_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_e_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _eh13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_eh13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _eh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_eh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _o_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_o_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _o_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_o_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _o_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_o_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _o_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_o_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _oh13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_oh13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _oh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_oh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _t_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_t_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _t_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_t_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _t_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_t_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _t_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_t_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _th13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_th13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _th3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_th3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _u_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_u_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _u_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_u_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _u_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_u_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _u_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_u_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _uh13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_uh13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _uh3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_uh3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _w_5w24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_w_5w24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _w_5w400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_w_5w400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _x_13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_x_13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _x_13d() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_x_13d", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _x_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_x_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _x_3b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_x_3b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _x_3d() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_x_3d", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à (tree node description)
        '''.
        '''</summary>
        Friend ReadOnly Property _z000000000000__new() As String
            Get
                Return ResourceManager.GetString("_z000000000000__new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property _zqm() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_zqm", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cube_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cube_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cube_left_end_0b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cube_left_end_0b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cube_left_end_1b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cube_left_end_1b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NodeKey	ParentKey	EN	FR
        '''==================== Who =======================================================
        '''ozzzp	ozzzy	Partenaires
        '''ozzzq	ozzzy	Investisseurs
        '''ozzzr	ozzzs	ZAAN.com
        '''ozzzs	ozzzy	Fournisseurs
        '''ozzzt	ozzzy	Concurrents
        '''ozzzu	ozzzy	Clients
        '''ozzzv	ozzzy	Banques
        '''ozzzw	ozzzy	Assureurs
        '''ozzzx	ozzzy	Administration
        '''==================== What ======================================================
        '''azzyq	azzyu	Projets
        '''azzyr	azzyu	Infrastructure
        '''azzys	azzyu	Assistance utilisateur
        '''azzyt	azzyu	Applicat [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property demo_tree_1() As String
            Get
                Return ResourceManager.GetString("demo_tree_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NodeKey	ParentKey	EN	FR
        '''==================== Who =======================================================
        '''ozzzp	ozzzy	Partners	Partenaires
        '''ozzzq	ozzzy	Investors	Investisseurs
        '''ozzzr	ozzzs	ZAAN.com	ZAAN.com
        '''ozzzs	ozzzy	Suppliers	Fournisseurs
        '''ozzzt	ozzzy	Competitors	Concurrents
        '''ozzzu	ozzzy	Customers	Clients
        '''ozzzv	ozzzy	Banks	Banques
        '''ozzzw	ozzzy	Insurers	Assureurs
        '''ozzzx	ozzzy	Administration	Administration
        '''==================== What ======================================================
        '''azzyq	azzyu	Pro [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property demo_tree_2() As String
            Get
                Return ResourceManager.GetString("demo_tree_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property down_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0017() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0017", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0047() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0047", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0048() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0048", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0082() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0082", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0085() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0085", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0530() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0530", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0531() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0531", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0541() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0541", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0545() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0545", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0546() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0546", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0547() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0547", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0578() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0578", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0583() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0583", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0587() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0587", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDE_0591() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDE_0591", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''to [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property gnu_gpl_v3() As String
            Get
                Return ResourceManager.GetString("gnu_gpl_v3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property go_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property go_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grey_empty800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey_empty800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_book_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_book_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_book_48i() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_book_48i", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property matrix_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matrix_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property matrix_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matrix_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Index	EN	FR
        '''1	When	Quand
        '''2	Who	Qui
        '''3	What	Quoi
        '''4	Where	Où
        '''5	Why	Pourquoi
        '''6	How	Comment
        '''7	Access control	Accès contrôlé
        '''8	found in : 	trouvés en : 
        '''9	Select in tree view	Sélectionner dans l&apos;arborescence
        '''10	Search folder	Rechercher dossier
        '''11	Search document	Rechercher document
        '''12	New document	Nouveau document
        '''13	Note	Note
        '''14	Texte	Texte
        '''15	Presentation	Présentation
        '''16	Spreadsheet	Feuille de calcul
        '''17	...	...
        '''18	Previous selection	Sélection précédente
        '''19	Next selection	Sélection suivante
        '''2 [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property messages() As String
            Get
                Return ResourceManager.GetString("messages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_doc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_doc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_docx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_docx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_ppt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_ppt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_pptx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_pptx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_xls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_xls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property new_xlsx() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("new_xlsx", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property next_f13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("next_f13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property next_f3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("next_f3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_z() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_z", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property origin_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("origin_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picture_black_90x90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_black_90x90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_bottom_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_bottom_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_bottom_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_bottom_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_cube_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_cube_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_cube_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_cube_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_import_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_import_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_import_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_import_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_left_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_left_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_left_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_left_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_right_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_right_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_right_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_right_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_top_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_top_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_top_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_top_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_tree_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_tree_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_tree_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_tree_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_view_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_view_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnl_view_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnl_view_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prev_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prev_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property prev_f13() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_f13", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property prev_f3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_f3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stop_z() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_z", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property turn_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("turn_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property turn_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("turn_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property up_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_cube_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_cube_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_cube_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_cube_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_details_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_details_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_details_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_details_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_icons_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_icons_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_icons_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_icons_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_tube_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_tube_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_tube_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_tube_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_42_btn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_42_btn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property zaan_cube_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property zaan_cube_16b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube_16b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property zaan_cube_20() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube_20", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube_50i() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube_50i", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube_qm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube_qm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube20_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube20_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube20_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube20_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube20_qm_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube20_qm_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zaan_cube20_qm_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zaan_cube20_qm_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ZAAN_pitch_EN_2015_02() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ZAAN_pitch_EN_2015_02", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ZAAN_pitch_FR_2015_02() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ZAAN_pitch_FR_2015_02", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Test 1
        '''.
        '''</summary>
        Friend ReadOnly Property zaan_test_1() As String
            Get
                Return ResourceManager.GetString("zaan_test_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Test 2
        '''.
        '''</summary>
        Friend ReadOnly Property zaan_test_2() As String
            Get
                Return ResourceManager.GetString("zaan_test_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property ZaanCubeIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ZaanCubeIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property ZaanCubeIconWin7all() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ZaanCubeIconWin7all", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
